/// Tabuleiro do Rio de Janeiro — 40 casas (plano §3.3: bairros reais).
/// Config estática local; a versão remota/versionada vem depois (§5.4).
///
/// Layout clássico: cantos em 0/10/20/30, 22 propriedades em 8 grupos de
/// cor, 6 companhias (transportes cariocas), 6 Sorte/Azar, imposto e lucros.
library;

import '../model/square.dart';

const List<SquareDef> rioBoard = [
  SquareDef(index: 0, name: 'Início', type: SquareType.inicio),
  SquareDef(
    index: 1,
    name: 'Bangu',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.rosa,
    price: 60,
    rentTable: [2, 10, 30, 90, 160, 250],
    housePrice: 50,
  ),
  SquareDef(index: 2, name: 'Sorte ou Azar I', type: SquareType.sorteAzar),
  SquareDef(
    index: 3,
    name: 'Campo Grande',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.rosa,
    price: 60,
    rentTable: [4, 20, 60, 180, 320, 450],
    housePrice: 50,
  ),
  SquareDef(index: 4, name: 'Imposto de Renda', type: SquareType.impostoDeRenda),
  SquareDef(
    index: 5,
    name: 'Estação de Metrô',
    type: SquareType.companhia,
    price: 200,
    companyFee: 25,
  ),
  SquareDef(
    index: 6,
    name: 'Madureira',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.azul,
    price: 100,
    rentTable: [6, 30, 90, 270, 400, 550],
    housePrice: 50,
  ),
  SquareDef(index: 7, name: 'Sorte ou Azar II', type: SquareType.sorteAzar),
  SquareDef(
    index: 8,
    name: 'Cascadura',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.azul,
    price: 100,
    rentTable: [6, 30, 90, 270, 400, 550],
    housePrice: 50,
  ),
  SquareDef(
    index: 9,
    name: 'Méier',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.azul,
    price: 120,
    rentTable: [8, 40, 100, 300, 450, 600],
    housePrice: 50,
  ),
  SquareDef(index: 10, name: 'Prisão (Visita)', type: SquareType.prisao),
  SquareDef(
    index: 11,
    name: 'Penha',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.vinho,
    price: 140,
    rentTable: [10, 50, 150, 450, 625, 750],
    housePrice: 100,
  ),
  SquareDef(
    index: 12,
    name: 'Barcas Rio-Niterói',
    type: SquareType.companhia,
    price: 150,
    companyFee: 20,
  ),
  SquareDef(
    index: 13,
    name: 'Olaria',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.vinho,
    price: 140,
    rentTable: [10, 50, 150, 450, 625, 750],
    housePrice: 100,
  ),
  SquareDef(
    index: 14,
    name: 'Ramos',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.vinho,
    price: 160,
    rentTable: [12, 60, 180, 500, 700, 900],
    housePrice: 100,
  ),
  SquareDef(
    index: 15,
    name: 'BRT Transcarioca',
    type: SquareType.companhia,
    price: 200,
    companyFee: 25,
  ),
  SquareDef(
    index: 16,
    name: 'Tijuca',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.laranja,
    price: 180,
    rentTable: [14, 70, 200, 550, 750, 950],
    housePrice: 100,
  ),
  SquareDef(index: 17, name: 'Sorte ou Azar III', type: SquareType.sorteAzar),
  SquareDef(
    index: 18,
    name: 'Vila Isabel',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.laranja,
    price: 180,
    rentTable: [14, 70, 200, 550, 750, 950],
    housePrice: 100,
  ),
  SquareDef(
    index: 19,
    name: 'Grajaú',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.laranja,
    price: 200,
    rentTable: [16, 80, 220, 600, 800, 1000],
    housePrice: 100,
  ),
  SquareDef(
      index: 20, name: 'Estacionamento Grátis', type: SquareType.estacionamento),
  SquareDef(
    index: 21,
    name: 'Santa Teresa',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.vermelho,
    price: 220,
    rentTable: [18, 90, 250, 700, 875, 1050],
    housePrice: 150,
  ),
  SquareDef(index: 22, name: 'Sorte ou Azar IV', type: SquareType.sorteAzar),
  SquareDef(
    index: 23,
    name: 'Lapa',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.vermelho,
    price: 220,
    rentTable: [18, 90, 250, 700, 875, 1050],
    housePrice: 150,
  ),
  SquareDef(
    index: 24,
    name: 'Centro',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.vermelho,
    price: 240,
    rentTable: [20, 100, 300, 750, 925, 1100],
    housePrice: 150,
  ),
  SquareDef(
    index: 25,
    name: 'VLT Carioca',
    type: SquareType.companhia,
    price: 200,
    companyFee: 25,
  ),
  SquareDef(
    index: 26,
    name: 'Flamengo',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.amarelo,
    price: 260,
    rentTable: [22, 110, 330, 800, 975, 1150],
    housePrice: 150,
  ),
  SquareDef(
    index: 27,
    name: 'Botafogo',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.amarelo,
    price: 260,
    rentTable: [22, 110, 330, 800, 975, 1150],
    housePrice: 150,
  ),
  SquareDef(
    index: 28,
    name: 'Bondinho do Pão de Açúcar',
    type: SquareType.companhia,
    price: 150,
    companyFee: 20,
  ),
  SquareDef(
    index: 29,
    name: 'Laranjeiras',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.amarelo,
    price: 280,
    rentTable: [24, 120, 360, 850, 1025, 1200],
    housePrice: 150,
  ),
  SquareDef(index: 30, name: 'Vá para a Prisão', type: SquareType.vaParaPrisao),
  SquareDef(
    index: 31,
    name: 'Urca',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.verde,
    price: 300,
    rentTable: [26, 130, 390, 900, 1100, 1275],
    housePrice: 200,
  ),
  SquareDef(
    index: 32,
    name: 'Jardim Botânico',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.verde,
    price: 300,
    rentTable: [26, 130, 390, 900, 1100, 1275],
    housePrice: 200,
  ),
  SquareDef(index: 33, name: 'Sorte ou Azar V', type: SquareType.sorteAzar),
  SquareDef(
    index: 34,
    name: 'Gávea',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.verde,
    price: 320,
    rentTable: [28, 150, 450, 1000, 1200, 1400],
    housePrice: 200,
  ),
  SquareDef(
    index: 35,
    name: 'Aeroporto Santos Dumont',
    type: SquareType.companhia,
    price: 200,
    companyFee: 25,
  ),
  SquareDef(index: 36, name: 'Sorte ou Azar VI', type: SquareType.sorteAzar),
  SquareDef(
    index: 37,
    name: 'Ipanema',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.roxo,
    price: 350,
    rentTable: [35, 175, 500, 1100, 1300, 1500],
    housePrice: 200,
  ),
  SquareDef(
      index: 38, name: 'Lucros e Dividendos', type: SquareType.lucrosDividendos),
  SquareDef(
    index: 39,
    name: 'Leblon',
    type: SquareType.propriedade,
    colorGroup: ColorGroup.roxo,
    price: 400,
    rentTable: [50, 200, 600, 1400, 1700, 2000],
    housePrice: 200,
  ),
];
